unopim/unopim

- packages/Webkul/Admin/src/DataGrids/Settings/ChannelDataGrid.php
The channel datagrid is now MariaDB compatible
> [MariaDB compatibility] Update ChannelDataGrid.php

- packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php
- packages/Webkul/Admin/src/DataGrids/Settings/ChannelDataGrid.php
- packages/Webkul/Admin/src/Resources/lang/fr_FR/app.php
Some correction to the app.php file french translation
> Some french updates in app.php file

- composer.lock
- packages/Webkul/Admin/src/DataGrids/Settings/ChannelDataGrid.php
- packages/Webkul/Admin/tests/Feature/Catalog/AttributeGroupTest.php
- packages/Webkul/Admin/tests/Feature/Catalog/AttributeTest.php
- packages/Webkul/Admin/tests/Feature/Catalog/CategoryTest.php
- packages/Webkul/Admin/tests/Feature/Catalog/CategoryValuesTest.php
- packages/Webkul/Admin/tests/Feature/Catalog/ProductTest.php
- packages/Webkul/Admin/tests/Feature/Catalog/ProductValuesTest.php
- packages/Webkul/Attribute/src/Database/Factories/AttributeFactory.php
- packages/Webkul/Attribute/src/Database/Factories/AttributeFamilyFactory.php
- packages/Webkul/Attribute/src/Database/Factories/AttributeOptionFactory.php
- packages/Webkul/Core/src/Database/Factories/ChannelFactory.php
- packages/Webkul/Product/src/Database/Factories/ProductFactory.php
- packages/Webkul/User/tests/Feature/UserTest.php
- test: update feature tests for category, product and attribute section
- fix: channel Datagrid not loading in db with table prefix due to raw queries
- update dependency phpoffice/phpspreadsheet in composer.lock for security patch
> Add Tests for Catalog Section

- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiAttributeFamilyTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiAttributeTest.php
- tests: Api test cases for Attribtue Family and Attribute
> Tests: Api test cases for Attribute Family and Attribute

- packages/Webkul/Admin/tests/Feature/Catalog/CategoryValuesTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiAttributeTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiCategoryFieldTest.php
- tests: Add api testcases for Category field and options
> tests: Add api testcases for Category field and options

- .env.example
- packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
- packages/Webkul/Admin/tests/Feature/Catalog/CategoryValuesTest.php
- packages/Webkul/Admin/tests/Feature/Catalog/ProductValuesTest.php
- packages/Webkul/AdminApi/src/Config/api-acl.php
- packages/Webkul/AdminApi/tests/Feature/Acl/ApiAclTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiAttributeFamilyTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiCategoryTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiConfigurableProductTest.php
- packages/Webkul/AdminApi/tests/Feature/Catalog/ApiProductTest.php
-- Create configurable product test cases
-- Create simple product test cases
-- Add more api acl test cases
-- Create category test cases
> Tests: Add api test cases for product and category

- packages/Webkul/Admin/tests/Feature/Acl/Configuration/IntegrationAclTest.php
- packages/Webkul/Admin/tests/Feature/Acl/DataTransfer/ExportAclTest.php
- packages/Webkul/Admin/tests/Feature/Acl/DataTransfer/ImportAclTest.php
- packages/Webkul/User/tests/Concerns/UserAssertions.php
Added the following test cases:
- integration section acl test cases
- import section acl test cases
- export section acl test cases
- job tracker grid acl test case
> tests: add ACL test cases for Configuration,Data transfer section

- packages/Webkul/Installer/src/Database/Seeders/Core/LocalesTableSeeder.php
- fixes issue #21 
- locale seeder throwing error when trying to delete a locale linked to a user
> fix: issue #21

- Changelog.md
- SECURITY.md
- packages/Webkul/Core/src/Core.php
- update changelog and security policy for version 0.1.3
> chore: update version to 0.1.3

- packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
- packages/Webkul/Admin/src/Http/Controllers/TinyMCEController.php
- packages/Webkul/Admin/src/Http/Controllers/User/AccountController.php
- packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
- packages/Webkul/Core/src/Filesystem/FileStorer.php
- packages/Webkul/Core/src/Traits/Sanitizer.php
- packages/Webkul/Product/src/Type/AbstractType.php
- Security fix: Cookie hijacking through Create User function
> Security fix: Stored XSS

- packages/Webkul/DataTransfer/src/Helpers/Importers/Category/Importer.php
- packages/Webkul/DataTransfer/src/Helpers/Importers/Product/Importer.php
- fix (product import): channel and locale wise value not merged correctly in case of update of multiple channel and locales
- fix (category import): locale wise value not merging correctly in case of update of multiple locale wise values
> fix: old and new values merging issue during import

- app/Exceptions/Handler.php
> feat: Add "Post Too Large" exception handling

- packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php
- packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
- removed product count from category datagrid 
- added loading shimmer for table body when grid is in loading state
> fix: add loading shimmer on category grid, remove product count 

- packages/Webkul/Product/src/Database/Factories/ProductFactory.php
- packages/Webkul/Product/src/Database/Migrations/2024_11_27_152754_add_status_column_to_products_table.php
Create a product by default the status will be enabled
-> First migrate the db with latest code.
-> Then create product
> fix: product status enabled by default

- packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
* Create an simple select attribute, with attribute_code and do not set attribute label.
* Now while creating the configurable product, attribute_code will be shown if label not set, for in the attribute lists to be used as variations.
> No attribute shown if label not set in creating variants

- packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
- packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php
- packages/Webkul/DataGrid/src/DataGrid.php
To quick export selected products only.
1) Select a few products from the product datagrid and then click Quick Export button.
2) Select the format from [xls, csv, xlsx].
3) Click on quick export button
> fix: quick export for selected products

- packages/Webkul/Admin/src/Resources/lang/fr_FR/app.php
- packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
Last french translation adujstements
> French translations improvements

- packages/Webkul/Attribute/src/Database/Migrations/2025_03_18_170321_alter_name_column_type_in_attribute_family_translations_table.php
- packages/Webkul/Attribute/src/Database/Migrations/2025_03_18_170404_alter_name_column_type_in_attribute_group_translations_table.php
- packages/Webkul/Attribute/src/Database/Migrations/2025_03_18_170449_alter_name_column_type_in_attribute_translations_table.php
- packages/Webkul/Attribute/src/Database/Migrations/2025_03_18_170603_alter_label_column_type_in_attribute_option_translations_table.php
- packages/Webkul/Category/src/Database/Migrations/2025_03_18_135047_alter_label_column_type_in_category_field_option_translations_table.php
- packages/Webkul/Category/src/Database/Migrations/2025_03_18_164318_alter_name_column_type_in_category_field_translations_table.php
* category_field_translations
* category_field_option_translations
* attribute_family_translations
* attribute_group_translations
* attribute_option_translations
* attribute_translations
> Alter text column to string (varchar) and add indexes

- packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php
> fix (elasticseach): category datagrid sort on id field instead of _id

- packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
- packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeFamilyController.php
- packages/Webkul/Admin/src/Http/Controllers/Catalog/Options/AjaxOptionsController.php
- packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php
- packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
- packages/Webkul/Admin/src/Resources/views/components/datagrid/filters.blade.php
- **[perf: optimize loading of product grid page with bulk family data](https://github.com/unopim/unopim/commit/ddcf74f0095df77d76282d298862ae6e6e4dbf64)(https://github.com/unopim/unopim/commit/ddcf74f0095df77d76282d298862ae6e6e4dbf64)**  
Optimized the loading of product grid by using an async select field for family in the product create modal and updating filters for the searchable dropdown in grid filters.
Created filter type for searchable dropdown in grid filters can be used in all grids
- **[perf: optimize family edit page to load attribute data with pagination](https://github.com/unopim/unopim/commit/2c744110b7e341fe03569eea4c38b919c47f0d4f)(https://github.com/unopim/unopim/commit/2c744110b7e341fe03569eea4c38b919c47f0d4f)**  
**[perf: optimize family create to handle bulk …
> Perf: Optmize loading of pages with bulk data

- packages/Webkul/Admin/src/Resources/lang/fi_FI/app.php
N/A
Fixed and updated Finnish translations.
N/A
N/A
N/A
> i18n: fix Finnish translations

- UPGRADE.md
- packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php
- packages/Webkul/Admin/src/Resources/views/components/products/dynamic-attribute-fields.blade.php
- packages/Webkul/Admin/tests/Feature/Catalog/ProductFilterWithElasticSearchTest.php
- packages/Webkul/ElasticSearch/src/Observers/Product.php
- packages/Webkul/Product/src/Filter/ElasticSearch/TextFilter.php
- upgrade.sh
Fixed: Label issue in product edit view checkbox type attribute.
Fixed: Product text type field filter in Elasticsearch.
Fixed: Category filter not working as expected in Elasticsearch.
Improvements and fixes related to Elasticsearch filtering in Product and Category
> Improved Elasticsearch filters for product and category

- packages/Webkul/DataTransfer/src/Helpers/Exporters/AbstractExporter.php
- packages/Webkul/DataTransfer/src/Helpers/Exporters/Category/Exporter.php
- packages/Webkul/DataTransfer/src/Helpers/Exporters/Product/Exporter.php
- packages/Webkul/DataTransfer/src/Helpers/Importers/FieldProcessor.php
- packages/Webkul/DataTransfer/src/Helpers/Importers/Product/Importer.php
1) Issue in product and category export job when exporting with media
2) Import job with media, due to path validation
> Issue fix for import and export jobs

- README.md
- packages/Webkul/DataTransfer/src/Helpers/Exporters/AbstractExporter.php
- packages/Webkul/DataTransfer/src/Helpers/Exporters/Category/Exporter.php
- packages/Webkul/DataTransfer/src/Helpers/Exporters/Product/Exporter.php
- packages/Webkul/DataTransfer/src/Helpers/Importers/FieldProcessor.php
- packages/Webkul/DataTransfer/src/Helpers/Importers/Product/Importer.php
- Category Export job fails due to missing file buffer initialisation
- Product Export job failing because of media directory for export not being found
> Export job issue due to 'with media' filter

- packages/Webkul/DataTransfer/src/Helpers/Import.php
- packages/Webkul/DataTransfer/src/Helpers/Importers/AbstractImporter.php
- packages/Webkul/DataTransfer/src/Jobs/Import/ImportTrackBatch.php
- use chunk for batches instead of loading all at once
- update timeout to 0 for ImportTrackBatch class
- set BATCH_SIZE to 100 instead of 1 for imports
- count batch through db instead of loading batches in memory
> Change import class timeout and batch size
